r"""What the two Alembic chains are and how to run one.

Shared by `test_migration_ownership.py`, which runs each chain against a
composed database, `test_migration_allowlists.py`, which checks the allowlists
and the wiring without needing one, `test_migration_chain.py`, which checks the
shape of each chain, and `test_migration_upgrade.py`, which applies one.
"""

import ast
import re
from collections.abc import Iterable
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from migrations.ownership import CE_TABLES

API_DIR = Path(__file__).resolve().parents[1]
CE_MIGRATIONS = API_DIR / "migrations"
CE_VERSION_TABLE = "alembic_version"
EE_VERSION_TABLE = "alembic_version_ee"

EE_TABLES = frozenset({"kpi", "kpi_history_point", "report", "external_access"})
"""The enterprise chain's allowlist, restated rather than imported.

The pack owns the authoritative copy in
`veodyn_enterprise.migrations.ownership`, and this suite has to run without the
pack installed, so it cannot import that copy. Nothing in THIS repository can
notice the two drifting apart: a test that imported the pack would skip here,
which is what the previous version of this line described as coverage. The
comparison lives in the pack, at `tests/test_allowlists_agree.py`, whose
pipeline checks out both trees.
"""

PRODUCT_TABLES = CE_TABLES | EE_TABLES
"""Both allowlists together: every table either chain owns."""

CE_REVISIONS = ("0013", "0012", "0011", "0010", "0009", "0006", "0005")
"""The community chain, newest first. Ids, not positions: these are stamped in
every existing database, so a renumbering orphans the stamp rather than tidying
anything.

Hand maintained on purpose, and deriving it from `versions/` would be the one
change to avoid: `test_the_community_revision_files_are_exactly_the_community
_chain` compares this tuple against those files, so a derived tuple would make
that assertion compare the files to themselves and pass whatever landed."""

CE_HEAD = CE_REVISIONS[0]
"""The newest community revision, named once. It was written out longhand in
three places, so adding a revision meant finding all three and the ones missed
failed as an unrelated-looking assertion about heads."""

CE_PREVIOUS = CE_REVISIONS[1]
"""One revision back from head, for the control in `test_migration_upgrade.py`
that has to seed a database deliberately behind."""

CE_SHIPPED_IDS = frozenset({"0010", "0009", "0006", "0005"})
"""Community ids that have been stamped in a real database, as a literal that is
**appended to, never edited**.

It exists because everything else about the chain is now derived from
`CE_REVISIONS`, including the head. That is convenient and it costs one guard:
a coordinated renumber (the file, its children, and the tuple) would leave every
other assertion green while orphaning the stamp in every database already
carrying the old id. Deriving this set too would reproduce exactly that hole, so
it is written out and `test_migration_chain.py` holds the chain to it.

Add an id here only once a revision has actually shipped. Removing one is the
error this guards."""

EE_REVISIONS = ("0008", "0007", "0004", "0003", "0002", "0001")
"""The enterprise chain, newest first."""

Diff = tuple[object, ...]


def chain_config(script_location: Path) -> Config:
    """A Config built in memory, so no `fileConfig` call reconfigures logging
    for the rest of the session."""
    config = Config()
    config.set_main_option("script_location", str(script_location))
    config.set_main_option("prepend_sys_path", str(API_DIR))
    config.set_main_option("path_separator", "os")
    return config


def ce_config() -> Config:
    return chain_config(CE_MIGRATIONS)


def ee_migrations() -> Path:
    pack = pytest.importorskip(
        "veodyn_enterprise",
        reason="the enterprise pack is not installed, so there is no second chain to compose with",
    )
    return Path(pack.__file__ or "").parent / "migrations"


def ee_config() -> Config:
    return chain_config(ee_migrations())


def version_files(migrations: Path) -> list[Path]:
    """Every revision file in a script directory, in filename order."""
    return sorted((migrations / "versions").glob("[0-9]*.py"))


def ce_version_files() -> list[Path]:
    return version_files(CE_MIGRATIONS)


def ee_version_files() -> list[Path]:
    return version_files(ee_migrations())


def declared_revisions(paths: Iterable[Path]) -> dict[str, str | None]:
    """Each revision file's own id mapped to the id it revises, read from the
    source rather than from a resolved revision map.

    Alembic refuses to build a map at all when a `down_revision` names an
    absent revision, so a test that only ever asks the map is a test that
    cannot describe the failure it is there to catch.
    """
    declared: dict[str, str | None] = {}
    for path in paths:
        assigned: dict[str, object] = {
            node.target.id: node.value.value
            for node in ast.walk(ast.parse(path.read_text()))
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and isinstance(node.value, ast.Constant)
        }
        revision = assigned.get("revision")
        assert isinstance(revision, str), f"{path.name} does not spell out its own revision id"
        assert "down_revision" in assigned, f"{path.name} does not spell out the revision it revises"
        parent = assigned["down_revision"]
        assert parent is None or isinstance(parent, str), f"{path.name} revises something that is not an id"
        declared[revision] = parent
    return declared


TABLE_ARGUMENTS: dict[str, tuple[tuple[int, str], ...]] = {
    "create_table": ((0, "table_name"),),
    "drop_table": ((0, "table_name"),),
    "rename_table": ((0, "old_table_name"), (1, "new_table_name")),
    "add_column": ((0, "table_name"),),
    "drop_column": ((0, "table_name"),),
    "alter_column": ((0, "table_name"),),
    "create_index": ((1, "table_name"),),
    "drop_index": ((1, "table_name"),),
    "create_primary_key": ((1, "table_name"),),
    "create_unique_constraint": ((1, "table_name"),),
    "create_check_constraint": ((1, "table_name"),),
    "create_foreign_key": ((1, "source_table"), (2, "referent_table")),
    "drop_constraint": ((1, "table_name"),),
}
"""Where each op names the table it acts on. Position and keyword, because a
revision may pass either, and `create_index` puts the index name first."""

NO_TABLE_OPS = frozenset({"f", "get_bind", "get_context", "inline_literal"})


def op_calls(source: str) -> list[tuple[str, ast.Call]]:
    """Every `op.<something>(...)` in a revision, with the something."""
    return [
        (node.func.attr, node)
        for node in ast.walk(ast.parse(source))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "op"
    ]


def literal_argument(call: ast.Call, index: int, keyword: str) -> str | None:
    node: ast.expr | None = None
    if len(call.args) > index:
        node = call.args[index]
    else:
        node = next((kw.value for kw in call.keywords if kw.arg == keyword), None)
    if node is None:
        return None
    assert isinstance(node, ast.Constant) and isinstance(node.value, str), (
        "a revision names a table with an expression rather than a literal, so ownership cannot be read off it"
    )
    return node.value


def tables_touched(source: str, known: frozenset[str] = PRODUCT_TABLES) -> set[str]:
    r"""Every table a revision creates, alters or writes, read from its source.

    Read out of the file rather than out of a database, so it holds before any
    of it has been applied anywhere.

    `known` exists for `op.execute`. Revision 0003 backfills
    `kpi.last_attempt_at` from `kpi_history_point` in raw SQL, and no AST walk
    can say which identifiers inside a string are table names, so that one case
    is matched by name against the set we own. Word boundaries make it exact:
    `\bkpi\b` does not match inside `kpi_history_point`, because `_` is a word
    character.

    An op this does not know is an assertion rather than a silent empty set. A
    revision that reached a table through an unmapped op would otherwise read
    as touching nothing at all, which is the one answer that makes every
    ownership test below it pass.
    """
    touched: set[str] = set()
    for attribute, call in op_calls(source):
        if attribute == "execute":
            for node in ast.walk(call):
                if isinstance(node, ast.Constant) and isinstance(node.value, str):
                    touched |= {name for name in known if re.search(rf"\b{re.escape(name)}\b", node.value)}
            continue
        if attribute in NO_TABLE_OPS:
            continue
        positions = TABLE_ARGUMENTS.get(attribute)
        assert positions is not None, f"tables_touched does not know where op.{attribute} names its table"
        for index, keyword in positions:
            name = literal_argument(call, index, keyword)
            if name is not None:
                touched.add(name)
    return touched


def upgrade_operations(config: Config) -> list[Diff]:
    """What this chain's own `env.py` proposes against the live database.

    `alembic check` is the real autogenerate: it runs `env.py`, so the filters
    under test are the ones the chain actually configures rather than a copy of
    them made by a test.
    """
    try:
        command.check(config)
    except AutogenerateDiffsDetected as detected:
        return list(detected.diffs)
    return []


def named_in(diff: object) -> set[str]:
    """Every table name a proposed operation mentions, whatever its shape.

    A diff is `("add_table", Table)`, `("remove_column", schema, table, Column)`
    or a nested list for a modified column, so the name is not at a fixed index.
    """
    names: set[str] = set()
    if not isinstance(diff, list | tuple):
        return names
    for element in diff:
        if isinstance(element, list | tuple):
            names |= named_in(element)
        elif isinstance(element, str):
            names.add(element)
        else:
            table = getattr(element, "table", element)
            name = getattr(table, "name", None)
            if isinstance(name, str):
                names.add(name)
    return names


def calls_named(tree: ast.AST, attribute: str) -> list[ast.Call]:
    """Every `something.<attribute>(...)` call in a parsed module."""
    return [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == attribute
    ]
