export const PARTS = [
  'provider',
  'portal',
  'root',
  'loading',
  'unavailable',
  'visualization',
  'problems',
  'empty',
  'tooltip',
  'legend',
  'legend-item',
  'chart',
  'table',
  'table-toolbar',
  'table-head',
  'table-row',
  'table-cell',
  'pagination',
  'counter',
  'counter-value',
  'counter-label',
  'counter-trend',
  'map',
  'map-popup',
  'heatmap',
  'heatmap-cell',
  'details',
] as const

export type Part = (typeof PARTS)[number]
