import type { MockAlert } from '../types/alerts'

export const mockAlerts: MockAlert[] = [
  {
    id: 1,
    name: 'AQI Exceeds Moderate',
    query_id: 2,
    query: { id: 2, name: 'Air Quality Index by Station', data_source_id: 1 },
    user: { id: 1, name: 'Admin User', email: 'admin@example.com' },
    options: { column: 'avg_aqi', op: 'greater than', value: 100, muted: false },
    state: 'ok',
    last_triggered_at: '2026-02-10T14:00:00Z',
    rearm: 3600,
    created_at: '2025-06-15T10:00:00Z',
    updated_at: '2026-03-17T14:30:00Z',
    destinations: [
      { id: 1, destination_id: 1, alert_id: 1, name: 'Team Email', type: 'email' },
    ],
  },
  {
    id: 2,
    name: 'Fleet Vehicles Below Threshold',
    query_id: 5,
    query: { id: 5, name: 'Fleet Vehicle Status Summary', data_source_id: 1 },
    user: { id: 1, name: 'Admin User', email: 'admin@example.com' },
    options: { column: 'total_vehicles', op: 'less than', value: 30, muted: false },
    state: 'ok',
    last_triggered_at: '2026-01-05T06:00:00Z',
    rearm: 86400,
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2026-03-18T06:00:00Z',
    destinations: [
      { id: 2, destination_id: 1, alert_id: 2, name: 'Team Email', type: 'email' },
      { id: 3, destination_id: 2, alert_id: 2, name: 'Ops Slack', type: 'slack' },
    ],
  },
  {
    id: 3,
    name: 'High Incident Count',
    query_id: 4,
    query: { id: 4, name: 'Traffic Incidents This Week', data_source_id: 1 },
    user: { id: 2, name: 'Jane Analyst', email: 'jane@example.com' },
    options: { column: 'incident_count', op: 'greater than', value: 50, muted: false },
    state: 'triggered',
    last_triggered_at: '2026-03-17T08:00:00Z',
    rearm: null,
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-03-17T08:00:00Z',
    destinations: [],
  },
  {
    id: 4,
    name: 'Bike Availability Low',
    query_id: 3,
    query: { id: 3, name: 'Bike Share Station Availability', data_source_id: 1 },
    user: { id: 3, name: 'Bob Developer', email: 'bob@example.com' },
    options: { column: 'bikes', op: 'less than', value: 2, muted: true },
    state: 'unknown',
    last_triggered_at: null,
    rearm: 1800,
    created_at: '2025-11-20T15:00:00Z',
    updated_at: '2025-12-01T10:00:00Z',
    destinations: [
      { id: 4, destination_id: 2, alert_id: 4, name: 'Ops Slack', type: 'slack' },
    ],
  },
  {
    id: 5,
    name: 'Temperature Spike Alert',
    query_id: 8,
    query: { id: 8, name: 'Weather & Temperature History', data_source_id: 1 },
    user: { id: 2, name: 'Jane Analyst', email: 'jane@example.com' },
    options: { column: 'temp_f', op: 'greater than', value: 100, muted: false },
    state: 'ok',
    last_triggered_at: '2025-09-05T15:00:00Z',
    rearm: 43200,
    created_at: '2025-04-01T08:00:00Z',
    updated_at: '2026-03-16T12:00:00Z',
    destinations: [
      { id: 5, destination_id: 1, alert_id: 5, name: 'Team Email', type: 'email' },
    ],
  },
]
