-- Captured rows for the local stack's warehouse, applied by compose/seed-catalog.py.
--
-- ROWS ONLY. The CREATE TABLE for each of these is generated by the seed script
-- from redash.historical.schema's own build_create_table_sql and map_column_type,
-- driven by the `columns` list in catalog.json. Hand-writing the DDL here would
-- be a second description of a table shape the fork already defines, and the
-- first schema change would leave the two disagreeing with nothing to notice.
--
-- __TABLE_<key>__ and __QID_<key>__ are substituted with the resolved historical
-- table name and Redash query id. Both are only known once the queries exist, so
-- neither can be written down here.
--
-- Timestamps are relative to now(), so a stack seeded today and one seeded in six
-- months both show recent coverage. A fixed date would age into a warehouse whose
-- freshest row is months old, which reads as a broken capture rather than a seed.

-- ── Bikeshare stations ──────────────────────────────────────────────────────
-- Dock inventory. Two captures a day apart: the set barely moves, which is what
-- makes it the reference dataset rather than a time series.
INSERT INTO __TABLE_bikeshare_stations__
  (captured_at, query_id, station_id, name, lat, lon, address, capacity) VALUES
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0001', 'Market St & 5th', 40.7411, -73.9897, '350 Market St', 31),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0002', 'Harbor Plaza', 40.7052, -74.0143, '1 Harbor Plaza', 24),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0003', 'Union Depot', 40.7506, -73.9935, '89 Depot Way', 47),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0004', 'Riverside Park North', 40.7987, -73.9721, 'Riverside Dr', 18),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0005', 'Civic Center', 40.7139, -74.0043, '22 Civic Sq', 39),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_stations__, 'ST-0006', 'University Gate', 40.7291, -73.9965, 'University Pl', 27),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0001', 'Market St & 5th', 40.7411, -73.9897, '350 Market St', 31),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0002', 'Harbor Plaza', 40.7052, -74.0143, '1 Harbor Plaza', 24),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0003', 'Union Depot', 40.7506, -73.9935, '89 Depot Way', 47),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0004', 'Riverside Park North', 40.7987, -73.9721, 'Riverside Dr', 18),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0005', 'Civic Center', 40.7139, -74.0043, '22 Civic Sq', 39),
  (now64(3) - INTERVAL 6 HOUR, __QID_bikeshare_stations__, 'ST-0006', 'University Gate', 40.7291, -73.9965, 'University Pl', 27);

-- ── Bikeshare availability ──────────────────────────────────────────────────
-- The time series half. Four captures over three days, with ST-0004 dropping to
-- zero bikes so an empty-state and an alert threshold both have something real
-- to fire on.
INSERT INTO __TABLE_bikeshare_availability__
  (captured_at, query_id, station_id, num_bikes_available, num_docks_available, is_renting, last_reported) VALUES
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0001', 12, 19, 1, 1),
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0002', 7, 17, 1, 1),
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0003', 25, 22, 1, 1),
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0004', 4, 14, 1, 1),
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0005', 18, 21, 1, 1),
  (now64(3) - INTERVAL 3 DAY, __QID_bikeshare_availability__, 'ST-0006', 9, 18, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0001', 15, 16, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0002', 5, 19, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0003', 31, 16, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0004', 0, 18, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0005', 22, 17, 1, 1),
  (now64(3) - INTERVAL 2 DAY, __QID_bikeshare_availability__, 'ST-0006', 11, 16, 1, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0001', 9, 22, 1, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0002', 11, 13, 1, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0003', 28, 19, 1, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0004', 0, 18, 0, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0005', 14, 25, 1, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_bikeshare_availability__, 'ST-0006', 13, 14, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0001', 17, 14, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0002', 8, 16, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0003', 19, 28, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0004', 6, 12, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0005', 20, 19, 1, 1),
  (now64(3) - INTERVAL 2 HOUR, __QID_bikeshare_availability__, 'ST-0006', 15, 12, 1, 1);

-- ── Transit vehicle positions ───────────────────────────────────────────────
-- Three lines, matching the route_labels on the transit data source, so a
-- colour-by-line visualization has more than one series.
INSERT INTO __TABLE_transit_vehicles__
  (captured_at, query_id, vehicle_id, route_id, line, latitude, longitude, bearing, speed, direction_id) VALUES
  (now64(3) - INTERVAL 1 DAY, __QID_transit_vehicles__, 'V-1041', '1', 'Blue Line', 40.7128, -74.0060, 91.0, 8.4, 0),
  (now64(3) - INTERVAL 1 DAY, __QID_transit_vehicles__, 'V-1042', '1', 'Blue Line', 40.7301, -73.9950, 273.0, 11.2, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_transit_vehicles__, 'V-2088', '2', 'Green Line', 40.7489, -73.9680, 12.0, 6.7, 0),
  (now64(3) - INTERVAL 1 DAY, __QID_transit_vehicles__, 'V-2089', '2', 'Green Line', 40.7612, -73.9776, 190.0, 9.9, 1),
  (now64(3) - INTERVAL 1 DAY, __QID_transit_vehicles__, 'V-3011', '3', 'Red Line', 40.7061, -74.0087, 45.0, 4.1, 0),
  (now64(3) - INTERVAL 4 HOUR, __QID_transit_vehicles__, 'V-1041', '1', 'Blue Line', 40.7190, -74.0021, 88.0, 12.6, 0),
  (now64(3) - INTERVAL 4 HOUR, __QID_transit_vehicles__, 'V-1042', '1', 'Blue Line', 40.7255, -73.9988, 268.0, 10.4, 1),
  (now64(3) - INTERVAL 4 HOUR, __QID_transit_vehicles__, 'V-2088', '2', 'Green Line', 40.7533, -73.9712, 15.0, 7.8, 0),
  (now64(3) - INTERVAL 4 HOUR, __QID_transit_vehicles__, 'V-2089', '2', 'Green Line', 40.7580, -73.9801, 187.0, 8.3, 1),
  (now64(3) - INTERVAL 4 HOUR, __QID_transit_vehicles__, 'V-3011', '3', 'Red Line', 40.7099, -74.0055, 47.0, 5.5, 0),
  (now64(3) - INTERVAL 30 MINUTE, __QID_transit_vehicles__, 'V-1041', '1', 'Blue Line', 40.7233, -73.9994, 90.0, 9.1, 0),
  (now64(3) - INTERVAL 30 MINUTE, __QID_transit_vehicles__, 'V-1042', '1', 'Blue Line', 40.7188, -74.0033, 271.0, 13.0, 1),
  (now64(3) - INTERVAL 30 MINUTE, __QID_transit_vehicles__, 'V-2088', '2', 'Green Line', 40.7566, -73.9744, 10.0, 6.2, 0),
  (now64(3) - INTERVAL 30 MINUTE, __QID_transit_vehicles__, 'V-2089', '2', 'Green Line', 40.7544, -73.9822, 192.0, 11.7, 1),
  (now64(3) - INTERVAL 30 MINUTE, __QID_transit_vehicles__, 'V-3011', '3', 'Red Line', 40.7133, -74.0021, 44.0, 3.8, 0);

-- ── Weather history ─────────────────────────────────────────────────────────
-- One row per capture, four days of them, so the coverage range on the dataset
-- page spans days rather than collapsing to a point.
INSERT INTO __TABLE_weather_history__
  (captured_at, query_id, name, temp, humidity) VALUES
  (now64(3) - INTERVAL 4 DAY, __QID_weather_history__, 'New York', 71.4, 58.0),
  (now64(3) - INTERVAL 3 DAY, __QID_weather_history__, 'New York', 68.9, 64.0),
  (now64(3) - INTERVAL 3 DAY + INTERVAL 8 HOUR, __QID_weather_history__, 'New York', 77.2, 49.0),
  (now64(3) - INTERVAL 2 DAY, __QID_weather_history__, 'New York', 66.1, 71.0),
  (now64(3) - INTERVAL 2 DAY + INTERVAL 9 HOUR, __QID_weather_history__, 'New York', 79.8, 44.0),
  (now64(3) - INTERVAL 1 DAY, __QID_weather_history__, 'New York', 70.3, 60.0),
  (now64(3) - INTERVAL 1 DAY + INTERVAL 7 HOUR, __QID_weather_history__, 'New York', 81.5, 41.0),
  (now64(3) - INTERVAL 8 HOUR, __QID_weather_history__, 'New York', 74.6, 53.0),
  (now64(3) - INTERVAL 1 HOUR, __QID_weather_history__, 'New York', 72.0, 57.0);
