// GENERATED by scripts/generate-feature-registry.mjs. Do not edit.
//
// Run `pnpm gen:features` after adding or removing a package directory under
// src/features/, or after changing a descriptor's `mockSlices`. The checked-in
// copy is asserted against the generator in generated-mock-slices.test.ts, so a
// stale one fails the suite.
//
// The mock store composes slices synchronously, so a descriptor cannot hand it
// one through its deferred loader: a slice carries ACTIONS, which have to be on
// the object create() builds at module scope. This file is where the
// descriptor's inert string specifier becomes a static import. See
// scripts/generate-mock-slices.mjs for the argument in full.
//
// ORDER IS BEHAVIOUR: emitted by feature package name, then in the order that
// descriptor lists them, because two slices declaring the same key resolve to
// whichever is spread last.

import type { StateCreator } from 'zustand'
import type { MockDataState } from './mock-data-store'

/**
 * What the installed features add to the mock store's state.
 *
 * Intersected into MockDataState, so a build with no feature package has a
 * store typed with exactly the community collections and actions in it and a
 * read of `state.kpis` does not compile.
 */
export type ContributedSlices = Record<never, never>

/** Nothing is installed, so nothing is contributed. */
export const createContributedSlices: StateCreator<MockDataState, [], [], ContributedSlices> = () => ({})
