// GENERATED by scripts/generate-feature-registry.mjs. Do not edit.
//
// Run `pnpm gen:features` after adding or removing a package directory under
// src/features/, or after changing a descriptor's `mockSlices`. The checked-in
// copy is asserted against the generator in generated-mock-slices.test.ts, so a
// stale one fails the suite.
//
// The mock store composes its slices synchronously, so an installed feature
// cannot hand it one through a descriptor's deferred loader: a slice carries
// ACTIONS, and those have to be on the object create() builds at module scope.
// The descriptor names its slice module as an inert STRING instead, and this
// file is where that string becomes a real static import. It is imported by
// src/stores/mock-data-store.ts and by nothing else, so no feature code
// reaches the pre-paint path through it, and in a build with no feature
// packages it is empty. See scripts/generate-mock-slices.mjs for the argument
// in full.
//
// ORDER IS BEHAVIOUR: slices are emitted by feature package name, then in the
// order that descriptor lists them. Two slices declaring the same key resolve
// to whichever is spread last, so this order is sorted rather than left to
// however the packages happened to be found.

import type { StateCreator } from 'zustand'
import type { MockDataState } from './mock-data-store'

/**
 * What the installed features add to the mock store's state.
 *
 * Intersected into MockDataState, so a build with no feature package has a
 * store typed with exactly the community collections and actions in it and a
 * read of `state.kpis` does not compile.
 */
export type ContributedSlices = Record<never, never>

/** Nothing is installed, so nothing is contributed. */
export const createContributedSlices: StateCreator<MockDataState, [], [], ContributedSlices> = () => ({})
