// GENERATED by scripts/generate-feature-registry.mjs. Do not edit.
//
// Run `pnpm gen:features` after adding or removing a package directory
// under src/features/. The checked-in copy is asserted against the
// generator in generated-registry.test.ts, so a stale one fails the suite.

import type { FeatureDescriptor } from './types'

/** Every feature package installed in this build. The stock build installs none. */
export const FEATURES: Record<string, FeatureDescriptor> = {}
