import { afterEach, describe, expect, it } from 'vitest'
import { screen } from '@testing-library/react'
import { renderWithProviders, resetStores } from '@/test/utils'
import {
  UserAvatar,
  USER_AVATAR_TESTID,
  avatarTintOf,
  initialsOf,
  isGravatarUrl,
} from './user-avatar'

afterEach(() => resetStores())

// Redash's synthesised URL, verbatim from models/users.py. This is what every
// real user record carries, so it is the case that matters most.
const GRAVATAR = 'https://www.gravatar.com/avatar/6f1ed002ab5595859014ebf0951522d9?s=40&d=identicon'
const CUSTOM = 'https://cdn.example.com/avatars/nick.png'

describe('isGravatarUrl', () => {
  it.each([
    ['the synthesised Redash URL', GRAVATAR],
    ['plain http', 'http://gravatar.com/avatar/abc'],
    ['the secure subdomain', 'https://secure.gravatar.com/avatar/abc'],
    ['a numbered CDN subdomain', 'https://2.gravatar.com/avatar/abc'],
    ['a protocol-relative URL', '//www.gravatar.com/avatar/abc'],
    ['upper case', 'HTTPS://WWW.GRAVATAR.COM/AVATAR/ABC'],
    ['a fully qualified trailing dot', 'https://gravatar.com./avatar/abc'],
  ])('recognises %s', (_label, url) => {
    expect(isGravatarUrl(url)).toBe(true)
  })

  it.each([
    ['gravatar.com only in the query string', 'https://evil.com/avatar.png?x=gravatar.com'],
    ['gravatar.com only in the path', 'https://evil.com/gravatar.com/avatar.png'],
    ['a host that merely ends with the string', 'https://mygravatar.com/a.png'],
    ['a lookalike parent domain', 'https://gravatar.com.evil.com/a.png'],
    ['an ordinary CDN', CUSTOM],
    ['a same-origin upload', '/uploads/avatars/7.png'],
    ['unparseable junk', 'not a url at all'],
    ['an empty string', ''],
    ['null', null],
    ['undefined', undefined],
  ])('rejects %s', (_label, url) => {
    expect(isGravatarUrl(url)).toBe(false)
  })
})

describe('initialsOf', () => {
  it.each([
    ['two words', 'Nick Sawinyh', 'NS'],
    ['one word', 'Cher', 'C'],
    // First-and-last, not the first two words: "AB" would read as a different
    // person's initials entirely.
    ['three words', 'Ada Byron Lovelace', 'AL'],
    ['padded and doubly spaced', '  Nick   Sawinyh  ', 'NS'],
    ['a lower case name', 'nick sawinyh', 'NS'],
    ['a non-Latin name', '日本 太郎', '日太'],
  ])('renders %s as %s', (_label, name, expected) => {
    expect(initialsOf(name)).toBe(expected)
  })

  it('keeps an astral character whole rather than half a surrogate pair', () => {
    const result = initialsOf('🙂 Anon')
    expect(result).toBe('🙂A')
    // A high surrogate with no low surrogate after it is the replacement-glyph
    // garbage that `word[0]` would have produced.
    expect(result).not.toMatch(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])/)
  })

  it.each([
    ['an empty name', ''],
    ['a whitespace-only name', '   '],
    ['a missing name', null],
  ])('falls back to the email local part for %s', (_label, name) => {
    expect(initialsOf(name, 'nick@veodyn.com')).toBe('N')
  })

  it('returns null when there is neither a name nor an email', () => {
    // Null, not '': the caller draws a person glyph instead of an empty circle.
    expect(initialsOf('', '')).toBeNull()
    expect(initialsOf(null, null)).toBeNull()
  })
})

describe('avatarTintOf', () => {
  it('is stable for a key', () => {
    // Swept rather than asked once: against a randomised implementation a
    // single comparison passes one time in eight, which is a test that mostly
    // cannot fail.
    for (let i = 0; i < 50; i += 1) {
      expect(avatarTintOf(String(i))).toBe(avatarTintOf(String(i)))
    }
  })

  it('separates two keys', () => {
    expect(avatarTintOf('7')).not.toBe(avatarTintOf('8'))
  })

  it('only ever returns a class from the chart-token pool', () => {
    // A tint outside the pool would not be generated by Tailwind and would
    // render as a transparent circle.
    for (let i = 0; i < 200; i += 1) {
      expect(avatarTintOf(String(i))).toMatch(/^bg-chart-[1-8]\/20$/)
    }
  })
})

describe('UserAvatar', () => {
  it('treats a gravatar URL as "no avatar" and issues no third-party request', () => {
    const { container } = renderWithProviders(
      <UserAvatar id={7} name="Nick Sawinyh" email="nick@veodyn.com" imageUrl={GRAVATAR} />
    )

    expect(screen.getByText('NS')).toBeInTheDocument()
    // The absence assertion is the whole test. Rendering the initials *and* the
    // image would still satisfy the line above while leaving the identicon on
    // screen and the email hash on its way to gravatar.com.
    expect(container.querySelector('img')).toBeNull()
  })

  it('renders a genuinely custom image', () => {
    const { container } = renderWithProviders(
      <UserAvatar id={7} name="Nick Sawinyh" email="nick@veodyn.com" imageUrl={CUSTOM} />
    )

    const img = container.querySelector('img')
    expect(img).toHaveAttribute('src', CUSTOM)
    expect(screen.queryByText('NS')).not.toBeInTheDocument()
  })

  it('renders initials when there is no image at all', () => {
    const { container } = renderWithProviders(
      <UserAvatar id={7} name="Nick Sawinyh" email="nick@veodyn.com" imageUrl={null} />
    )

    expect(screen.getByText('NS')).toBeInTheDocument()
    expect(container.querySelector('img')).toBeNull()
  })

  it('keys the colour off the id, so editing a name does not repaint the avatar', () => {
    const first = renderWithProviders(<UserAvatar id={7} name="Nick Sawinyh" />)
    const before = screen.getByTestId(USER_AVATAR_TESTID).className
    first.unmount()

    renderWithProviders(<UserAvatar id={7} name="Nicholas Sawinyh" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID).className).toBe(before)
    expect(before).toContain('bg-chart-7/20')
  })

  it('gives two different people two different colours', () => {
    const first = renderWithProviders(<UserAvatar id={7} name="Same Name" />)
    const before = screen.getByTestId(USER_AVATAR_TESTID).className
    first.unmount()

    renderWithProviders(<UserAvatar id={8} name="Same Name" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID).className).not.toBe(before)
  })

  it('falls back to the name for the colour when there is no id', () => {
    renderWithProviders(<UserAvatar name="Nick Sawinyh" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID)).toHaveClass(avatarTintOf('Nick Sawinyh'))
  })

  it('draws a person glyph rather than an empty circle when nothing is known', () => {
    renderWithProviders(<UserAvatar id={7} name="" email="" />)

    const avatar = screen.getByTestId(USER_AVATAR_TESTID)
    expect(avatar.textContent).toBe('')
    expect(avatar.querySelector('svg')).toHaveClass('lucide-user')
  })

  it('is decorative by default, because the name is already visible beside it', () => {
    renderWithProviders(<UserAvatar id={7} name="Nick Sawinyh" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID)).toHaveAttribute('aria-hidden', 'true')
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
  })

  it('takes an accessible name when asked for one', () => {
    renderWithProviders(<UserAvatar id={7} name="Nick Sawinyh" alt="Nick Sawinyh" />)
    expect(screen.getByRole('img', { name: 'Nick Sawinyh' })).toBeInTheDocument()
  })

  it('renders at the requested size', () => {
    const first = renderWithProviders(<UserAvatar id={7} name="Nick Sawinyh" size="lg" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID)).toHaveClass('size-16')
    first.unmount()

    renderWithProviders(<UserAvatar id={7} name="Nick Sawinyh" />)
    expect(screen.getByTestId(USER_AVATAR_TESTID)).toHaveClass('size-7')
  })
})
