{{- $app := .Values.appName | default .Chart.Name }}
{{- if hasKey .Values $app }}
{{- with (index .Values $app) }}
  {{- if .onePasswordItemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $.Release.Name }}-secret
spec:
  itemPath: "{{ .onePasswordItemPath }}"
  {{- end }}
{{- end }}
{{- end }}
