// GENERATED by scripts/generate-plugin-registry.mjs. Do not edit.
//
// Run `pnpm gen:plugins` after adding or removing a package directory
// under src/plugins/. The checked-in copy is asserted against the
// generator in generated-registry.test.ts, so a stale one fails the suite.

import { register as register_example } from './example'

/** Every plugin package installed in this build, by directory name. */
export const PLUGIN_PACKAGES: Record<string, () => void> = {
  'example': register_example,
}
